# @package __global__

# This file is based on implementations from audiocraft's configs:
# https://github.com/facebookresearch/audiocraft/blob/main/audiocraft/config/solver/*.yaml
# In order to use it,
# this file should be copied into your local audiocraft repo to ../audiocraft/config/solver/flow_dpo/flow_dpo_jasco.yaml

# Solver for a fine-tuning of JASCO (text-to-music) with 
# Multi-Reward Direct Preference Optimization (MR-FlowDPO) on an
# MRSD (Multi-Reward Strong Domination) dataset.

defaults:
  - musicgen/default
  - /model: lm/musicgen_lm
  - override /conditioner: jasco_chords_drums
  - override /dset: dpo/jasco_mrsd_pairs
  - _self_

lm_model: flow_matching
solver: flow_dpo

autocast: true
autocast_dtype: float16

compression_model_checkpoint: //pretrained/facebook/encodec_32khz
# precomputed mean std accross training data sub-partition
compression_model_latent_std: 4.0102
compression_model_latent_mean: -0.0074
compression_model_framerate: 50
compression_model_latent_dim: 128 

efficient_attention_backend: xformers # restricted attention implementation supports only xformers at the moment

channels: 1
sample_rate: 32000

deadlock:
  use: true  # deadlock detection

dataset:
  segment_duration: 10
  batch_size: 32
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way
  compression_model_framerate: ${compression_model_framerate}

optim:
  epochs: 500
  optimizer: adamw
  lr: 1e-4
  ema:
    use: true
    updates: 10
    device: cuda

dpo:
  beta: 2000.0

logging:
  log_tensorboard: true

schedule:
  lr_scheduler: cosine
  cosine:
    warmup: 4000
    lr_min_ratio: 0.0
    cycle_length: 1.0

transformer_lm:
  causal: false
  skip_connections: false
  flow_dim: ${compression_model_latent_dim}
  chords_dim: ${conditioners.chords.chords_emb.out_dim}
  drums_dim: ${conditioners.self_wav.drum_latents.out_dim}

generate:
  lm: 
    max_prompt_len: null
    max_gen_len: null
    remove_prompts: false
    cfg_coef_all: 5.0
    cfg_coef_txt: 0.0
    prompted_samples: false
    samples:
      prompted: false
      unprompted: true

conditioners:
  self_wav:
    drum_latents:
      compression_model_latent_dim: ${compression_model_latent_dim}
      compression_model_framerate: ${compression_model_framerate}
      segment_duration: ${dataset.segment_duration}
